skip = [
    "julia",
    "BugReporting", # nested rr is not supported

    # deprecated
    "NeuralNetDiffEq",
    "DiffEqBiological",
    "DiffEqMonteCarlo",
    "DiffEqPDEBase",
    "CUDAnative",
    "CUDAatomics",
    "CuArrays",
    "CUDAdrv",
    "CUDAapi",
    "AMDGPUnative",
    "ROCArrays",
    "GPUifyLoops",

    # requires binaries
    "MATLAB",               # MATLAB
    "MATLABDiffEq",         # MATLAB
    "deSolveDiffEq",        # R
    "FEniCS",               # Docker
    "ClimateMachine",       # MPI
    "MPI",                  # MPI
    "BitemporalPostgres",   # POSTGRES

    # doing bad things
    # intentionally throwing a segfault
    "Run",
    # crashes not caused by Julia
    "ConnectFourSolver",    # artifact unsuited for julia#master
    "Minuit2",              #
    "OpenCV",               #
    "CDDLib",               # segfault in called library
    "Elemental",            #
    "Starlight",            #
    # doing bad stuff during precompilation
    "NewsLookout",          # writing to a file in the package dir
    # using a Cassette pass that generates invalid IR
    "Traceur",
    "IBMQJulia",
    # using overly complex types/tuples
    "Salsa",

    # requires specific environment
    "AWSS3",                # AWS secrets
    "AWSCRT",               #
    "AWSTools",             #
    "LibAWSCRT",            #
    "GPUInspector",         # GPU hardware
    "CUDA",                 # CUDA hardware
    "ArrayInterfaceCUDA",   #
    "NNlibCUDA",            #
    "BloqadeCUDA",          #
    "FoldsCUDA",            #
    "LinearSolveCUDA",      #
    "oneAPI",               # oneAPI hardware
    "AMDGPU",               # AMD GPU hardware
    "HSARuntime",
    "AdalmPluto",           # SDR hardware
    "RemoteHPC",            # server software
    "Metal",                # Apple hardware
    "ObjectiveC",           # macOS
    
    # nested containerization not supported
    # (triggers a bug in crun)
    "Sandbox",
    "BinaryBuilder",
    "BinaryBuilderBase",
]

# packages that are incompatible with running under rr
skip_rr = [
    "Plots",                        # hangs
    "BinaryBuilderBase",            # requires 32-bit rr
]

# packages that are slow, and should be granted more test time (they're worth it)
slow = [
    "PackageCompiler",
    "ChainRules"
]
