["General"]
url = "https://github.com/JuliaRegistries/General.git"
uuid = "23338594-aafe-5451-b93e-139f81909106"
skip = [
    "julia",
    "MATLAB", # Requires MATLAB
    "MATLABDiffEq", # Requires MATLAB
    "deSolveDiffEq", # Requires R
    "FEniCS", # Requires Docker Installation
    "NeuralNetDiffEq", # Deprecated
    "DiffEqBiological", # Deprecated
    "DiffEqMonteCarlo", # Deprecated
    "DiffEqPDEBase", # Deprecated
    "ClimateMachine", # Requires MPI
    "MPI", # Requires MPI
    "CUDAnative", # Deprecated
    "OptionalArgChecks", # broken, generates invalid IR
]
retry = [
    "EcologicalNetworks",
    "FixedEffectModels",
    "GLM",
    "SpatialJackknife",
    "StatsModels",
    "UncertainData",
    "StressTest",
    "StateSpaceReconstruction",
    "PolyChaos",
    "RoME",
]
