["General"]
url = "https://github.com/JuliaRegistries/General.git"
skip = [
    "AbstractAlgebra", # Hangs forever
    "ChangePrecision", # Hangs forever
    "Chunks", # Hangs forever
    "DiscretePredictors", # Hangs forever
    "DotOverloading",
    "DynamicalBilliards", # Hangs forever
    "Electron",
    "Embeddings",
    "GeoStatsDevTools",
    "HCubature",
    "IndexableBitVectors",
    "LatinHypercubeSampling", # Hangs forever
    "LazyCall", # deleted, hangs
    "LazyContext",
    "LinearLeastSquares", # Hangs forever
    "MeshCatMechanisms",
    "NumberedLines",
    "OrthogonalPolynomials", # Hangs forever
    "Parts", # Hangs forever
    "Rectangle", # Hangs forever
    "RecurUnroll", # deleted, hangs
    "RequirementVersions",
    "SLEEF", # Hangs forever
    "SequentialMonteCarlo",
    "SessionHacker",
    "TypedBools", # deleted, hangs
    "ValuedTuples",
    "ZippedArrays", # Hangs forever
]
okay = [
    "BinDeps", # Not really ok, but packages may list it just as a fallback
    "Compat",
    "Homebrew",
    "InteractiveUtils", # We rely on LD_LIBRARY_PATH working for the moment
    "LinearAlgebra", # Takes too long
    "NamedTuples", # As requested by quinnj
    "WinRPM",
]
