name: CI

on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} - Running ${{ matrix.test_julia }} ${{ matrix.test_buildflags }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.10', '1.11']
        os: ['ubuntu-latest']
        arch: [x64]
        test_julia: ['']
        test_buildflags: ['']
        include:
          # special releases
          - os: 'ubuntu-latest'
            arch: 'x64'
            version: '1.10'
            test_julia: 'nightly'
          - os: 'ubuntu-latest'
            arch: 'x64'
            version: '1.10'
            test_julia: 'stable'
          # directly from Git, likely built by CI
          - os: 'ubuntu-latest'
            arch: 'x64'
            version: '1.10'
            test_julia: 'master~10'
          # directly from Git, force a build (see below)
          - os: 'ubuntu-latest'
            arch: 'x64'
            version: '1.10'
            test_julia: 'master'
            test_buildflags: 'JULIA_CPU_TARGET=native JULIA_PRECOMPILE=0'
    env:
      JULIA_DEBUG: PkgEval
      JULIA: ${{ matrix.test_julia }}
      BUILDFLAGS: ${{ matrix.test_buildflags }}
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          BUILDKITE_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
